### ISSUE TITLE
kdeploy not found?

### ISSUE THREAD

**Issue by gardner** [kaiostech/sample-vue#2]
kdeploy is not availabel on npm https://www.npmjs.com/package/kdeploy and the github repo has been removed.

**Comment by gardner** [comment]
More specifically:

    $ npm i 
    npm WARN deprecated fsevents@2.0.6: Please update: there are crash fixes
    npm ERR! Error while executing:
    npm ERR! /usr/local/bin/git ls-remote -h -t ssh://git@github.com/kaiostech/kdeploy.git
    npm ERR! 
    npm ERR! ERROR: Repository not found.
    npm ERR! fatal: Could not read from remote repository.
    npm ERR! 
    npm ERR! Please make sure you have the correct access rights
    npm ERR! and the repository exists.
    npm ERR! 
    npm ERR! exited with error code: 128

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/gardner/.npm/_logs/2019-10-23T21_07_04_781Z-debug.log

**Comment by seinlin** [comment]
Resolved.

**Comment by metaspartan** [comment]
This does not seem to be resolved, the repo is still missing and so is the npm package.

**Comment by Filipe-Souza** [comment]
Posted a possible solution for this case on [this issue](https://github.com/kaiostech/sample-vanilla/issues/1#issuecomment-627663107)
